=== D-Lizana/Clases-HTML5-CSS-y-XML/XML/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="clientes">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="cliente" maxOccurs="unbounded">
                <xs:complexType>    
                    <xs:sequence>
                        <xs:element name="nombre">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="1"/>
                                    <xs:maxLength value="50"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="correo" >
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="telefono">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{10}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

            <xs:element name="web">
                <xs:simpleType>
                  <xs:restriction base="xs:anyURI" />
                </xs:simpleType>
              </xs:element>

        </xs:sequence>
    </xs:complexType>
</xs:element>

</xs:schema>

=== D-Lizana/Clases-HTML5-CSS-y-XML/XML/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clientes.xsd">
    <cliente>
        <nombre>Denis</nombre>
        <correo>denis@uax.es</correo>
        <telefono>666666666</telefono>
        <web>www.denis.com</web>
    </cliente>
    <cliente>
        <nombre>Ivan</nombre>
        <correo>ivan@uax.es</correo>
        <telefono>666999666</telefono>
        <web>www.ivan.com</web>
    </cliente>
    <cliente>
        <nombre>Efr√©n</nombre>
        <correo>efren@uax.es</correo>
        <telefono>699666666</telefono>
        <web>www.efren.com</web>
    </cliente>

</clientes>
